# Generated by Django 5.0.2 on 2024-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
