# Generated by Django 5.0.2 on 2024-10-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_evaluator_date_remove_evaluator_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorreport',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
